# Generated by Django 3.1.5 on 2021-03-14 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='OrderPlaced',
        ),
    ]
